import { getCurrentUserAction } from '@/actions/auth.actions';
import { AppShell } from '@/components/layout/AppShell'; // <-- Import the shell
import { AuthProvider } from '@/providers/auth-provider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Project Management System',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const authRes = await getCurrentUserAction();
	const currentUser = authRes.success ? authRes.data : null;
	return (
		<html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col">
				{/* Wrap children in the AppShell */}

				<AuthProvider initialUser={currentUser}>
					<AppShell>{children}</AppShell>
				</AuthProvider>
			</body>
		</html>
	);
}
