import { NavBar } from '@/components/shared/navbar/NavBar';
import { MobileNav } from '@/components/shared/navbar/mobile-nav';
import { Sidebar } from '@/components/shared/sidebar/Sidebar';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Project Management System',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col">
				<div className="flex h-screen bg-[#f8fafc] text-slate-900 overflow-hidden font-sans">
					{/* 1. DESKTOP SIDEBAR */}
					<Sidebar />

					<div className="flex-1 flex flex-col min-w-0">
						{/* 2. TOP Navigation Bar (Search & Actions) */}
						{/* navbar goes here */}
						<NavBar />
						{/* 3. MAIN CONTENT AREA */}
						<main className="flex-1 overflow-y-auto pb-20 md:pb-0">
							<div className="max-w-7xl mx-auto p-4 sm:p-6 lg:p-8">{children}</div>
						</main>
					</div>

					{/* 4. MOBILE BOTTOM NAV */}
					<MobileNav />
				</div>
			</body>
		</html>
	);
}
